puts ''
puts '         Entering commands:'
puts '   `1b to 3c` will move a white knight      Enter `save`'
puts '                 or                       to save the game'
puts '   `d7 to d5` will move a black pawn '
